# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username="vagrant"
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", type: "dhcp"


  config.vm.synced_folder "./../", "/home/vagrant/public_html",
    type: "rsync", 
    rsync__exclude: [".git/", "**/.DS_Store"]
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  
  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = '151c90d97474655fff84ff40d1f78e1cea029b52da82f0b293a8e83855e634ce'
    provider.image = 'Ubuntu 14.04 x64'
    provider.region = 'nyc2'
    provider.size = '512mb'
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yaml"
  end
  
end
